const express = require("express");
const router = express.Router();
const mongoose = require("mongoose");
const { Collection } = require("../models/collection");
// const auth = require("../middleware/auth");
const locArray = [
  "Abandoned Factory ",
  "Abandoned Mine ",
  "Abandoned Office ",
  "Abandoned Quarry ",
  "Abandoned Road ",
  "Abandoned Subway",
  "Abandoned Warehouse ",
  "Abbey",
  "Academy",
  "Active Volcano ",
  "Aerie ",
  "Aero Club",
  "Aerodrome ",
  "Agricultural Equipment Center",
  "Agricultural Experiments Facility",
  "Agricultural Service Center ",
  "Air Cargo Terminal ",
  "Air Passenger Terminal ",
  "Air Purification Plant",
  "Air Show",
  "Airborne Aircraft ",
  "Airborne Research Facility ",
  "Aircraft Bunker",
  "Aircraft Carrier ",
  "Aircraft Charter",
  "Aircraft Graveyard",
  "Aircraft Museum",
  "Aircraft on the Ground ",
  "Aircraft Repair Facility ",
  "Aircraft Service Center",
  "Aircraft Test & Simulations Facility ",
  "Airline Offices ",
  "Airpark",
  "Airport Control Tower ",
  "Airport Hangar ",
  "Airship ",
  "Airstrip",
  "Alarm Monitoring Center ",
  "Alter",
  "Amphibious Vehicle ",
  "Amphitheatre",
  "Amusement Park",
  "Amusement Park ",
  "An Abandoned Ship ",
  "Anchorage",
  "Anchorage or Mooring",
  "Ancient Battleground ",
  "Ancient Ruins ",
  "Animal Hospital ",
  "Animal Shelter ",
  "Animal Trail",
  "Animal Trainer ",
  "Annex",
  "Anomalous Mine",
  "Antique Aircraft Airfield",
  "Apartment Tower",
  "Aquarium ",
  "Aquatic Preserve",
  "Aqueduct ",
  "Arch Bridge ",
  "Archaeology Dig Site ",
  "Archipelago",
  "Arctic Fishing Cabin",
  "Arena ",
  "Armory ",
  "Arsenal ",
  "Art Gallery ",
  "Art Institute",
  "Art Museum ",
  "Art School ",
  "Artic Expedition HQ ",
  "Auction House ",
  "Audio Recording Studio ",
  "Auto Body Shop",
  "Auto Dealership ",
  "Auto Parts Shop ",
  "Automobile Graveyard",
  "Automobile Manufacturing Complex",
  "Automobile Museum",
  "Automobile Race Track",
  "Automobile Tunnel",
  "Aviary ",
  "Badlands ",
  "Bail Bond House ",
  "Ballet Studio ",
  "Ballroom ",
  "Banquet Facility ",
  "Bar ",
  "Barbershop ",
  "Barge",
  "Barn ",
  "Barracks",
  "Baseball Park",
  "Baseball Stadium",
  "Basement ",
  "Basin",
  "Basketball Arena",
  "Bathhouse",
  "Battle Field ",
  "Battleship ",
  "Bay ",
  "Bayou ",
  "Beach House ",
  "Beached Shipwreck ",
  "Beam Bridge ",
  "Beauty Salon ",
  "Bed & Breakfast ",
  "Beneath a Bridge ",
  "Bermuda Triangle",
  "Bible Institute",
  "Billiard Hall ",
  "Bluffs",
  "Boat Dealership ",
  "Boat House",
  "Boat Ramp",
  "Boat Taking on Water",
  "Bog ",
  "Bookshop ",
  "Border Crossing ",
  "Botanical Garden",
  "Bowling Alley ",
  "Box Canyon",
  "Brewery ",
  "Bridge",
  "Broadcast Tower ",
  "Bull Fighting Ring ",
  "Bungalow",
  "Bunker ",
  "Burial Mound",
  "Bus Depot",
  "Bus Station ",
  "Bus Stop ",
  "Bus Terminal ",
  "Busy Intersection",
  "Butcher Shop ",
  "Butte ",
  "Cabaret/Supper Club",
  "Cabin",
  "Cable Company",
  "Cable Television Company ",
  "Cable-Stayed Bridge ",
  "Cafeteria ",
  "Caldera",
  "Campground ",
  "Camping Area ",
  "Canal ",
  "Candy Factory ",
  "Cantilever Bridge ",
  "Canyon Mouth",
  "Cape ",
  "Car Wash ",
  "Cargo Aircraft ",
  "Cargo Container ",
  "Cargo Plane ",
  "Cargo Terminal ",
  "Carnival",
  "Casino ",
  "Castle ",
  "Cathedral ",
  "Causeway",
  "Cave",
  "Caverns ",
  "Cemetery ",
  "Cenote ",
  "Central Park",
  "Chalet ",
  "Chamber of Commerce ",
  "Chapel",
  "Chasm",
  "Checkpoint ",
  "Chemical Dump ",
  "Chemical Plant ",
  "Chemical Storage Facility",
  "Chemical Tanker Ship",
  "Chicken Farm",
  "Children's Hospital",
  "Children's Museum",
  "Chinese Junk (Sailing Ship)",
  "Chiropractic Clinic",
  "Church ",
  "Church Camp",
  "Church Tower ",
  "Cinema ",
  "Circus",
  "Citadel ",
  "Citrus Grove",
  "City",
  "City Center",
  "City Hall ",
  "Civic Center",
  "Clandestine Drug Lab",
  "Cliff",
  "Clinic ",
  "Clock Tower ",
  "Club House ",
  "Coal Mine ",
  "Coal Processing Plant",
  "Coal-Fired Power Plant ",
  "Coastal Game Preserve ",
  "Coastal Island ",
  "Coastal Marsh",
  "Coastal Resort",
  "Coastal Shallows ",
  "Coastline ",
  "Cocktail Lounge ",
  "Coffee House",
  "Collapsed Bridge ",
  "Collapsed Mine ",
  "Collapsed Tunnel ",
  "Collection Agency ",
  "College ",
  "Colonial Style Residence",
  "Combination Office/Warehouse",
  "Commercial Construction Area ",
  "Community Building",
  "Community College Complex",
  "Commuter Train ",
  "Concert Hall ",
  "Concrete",
  " Sand",
  " & Gravel Company ",
  "Condominium Tower",
  "Conference ",
  "Construction Crane",
  "Container Ship",
  "Convenience Store ",
  "Convent ",
  "Convention Center ",
  "Coral Reef ",
  "Correctional Institute Airport",
  "Correctional Institution",
  "Country Club ",
  "Country Store",
  "Courthouse ",
  "Cove ",
  "Covered Bridge ",
  "Cow Camp",
  "Crater",
  "Credit Union ",
  "Crematorium",
  "Crystal Mine ",
  "Culinary Institute ",
  "Culvert ",
  "Cypress Swamp",
  "Dairy Farm ",
  "Dam ",
  "Dance Club ",
  "Dance Hall ",
  "Dance Studio ",
  "Data Storage & Processing Center ",
  "Deep Canyon ",
  "Deep Canyon Bridge",
  "Deep Earth Exploration Facility ",
  "Deep in the Earth",
  "Deep Sea Trench",
  "Deep Sea Tugboat (Ship)",
  "Deep-Sea Research Submarine",
  "Delta",
  "Dense Jungle",
  "Dental Center ",
  "Department of Corrections Medical Center",
  "Department Store ",
  "Desert ",
  "Desert Basin",
  "Desert Flats ",
  "Desert Hills",
  "Desert Isle ",
  "Deserted Island",
  "Destroyer ",
  "Detention Facility",
  "Diamond Field",
  "Dike",
  "Diner ",
  "Dirigible ",
  "Distillery ",
  "District Office",
  "Ditch",
  " or Small Canal",
  "Dive Boat ",
  "Dog Racing Track ",
  "Drag Strip ",
  "Drainage Canal",
  "Drive-In Movie Theatre ",
  "Drive-in Restaurant",
  "Drug & Alcohol Abuse Treatment Facility ",
  "Drug Laboratory ",
  "Dry Cleaner ",
  "Dry Dock ",
  "Dry Flood Channel",
  "Dry Gulch or Canyon",
  "Dry Riverbed ",
  "Dungeon ",
  "Election Headquarters ",
  "Electric Company",
  "Electric Company ",
  "Electrical Storm",
  "Electronics Manufacturer ",
  "Elementary School ",
  "Elevated Train ",
  "Embassy",
  "Emergency Response Center ",
  "Emergency Shelter ",
  "Engine House (Train)",
  "Engine Repair Shop ",
  "Environmental Rally ",
  "Esplanade ",
  "Estate ",
  "Estuary ",
  "Excavation ",
  "Exibition Center",
  "Exotic Restaurant ",
  "Experimental Facility ",
  "Experimental Station",
  "Experimental Vehicle ",
  "Exploration Submarine ",
  "Extra-Dimensional Gate ",
  "Factory ",
  "Fair",
  "Fallen Log Foot Bridge ",
  "Fallout Shelter ",
  "Falls",
  "Farm ",
  "Farm Equipment Dealership ",
  "Fast Food Restaurant ",
  "Ferris Wheel ",
  "Ferry Boat ",
  "Ferry Embarkation Point ",
  "Ferryboat ",
  "Festival",
  "Festival",
  "Filtration Plant",
  "Fine Dining Restaurant ",
  "Fire Academy",
  "Fire Department ",
  "Fire Station",
  "Fire Watchtower",
  "Fireworks Display ",
  "Fish Farm",
  "Fish Hatchery",
  "Fishing Boat ",
  "Fishing Lodge",
  "Fishing Pier",
  "Fishing Trawler (Small Ship)",
  "Fitness Center",
  "Fitness Center ",
  "Fixed Radar Site ",
  "Fjord",
  "Flats",
  "Flea Market ",
  "Flight School ",
  "Floating Casino ",
  "Floating Crane (Ship)",
  "Floating Dock ",
  "Floating Drydock (Ship)",
  "Flooded Bridge ",
  "Flooded Building",
  " or Structure ",
  "Flooded River ",
  "Florist or Flower shop ",
  "Foot Bridge ",
  "Football Stadium",
  "Foothills ",
  "Foreign Restaurant ",
  "Forest ",
  "Forest Fire ",
  "Forested Hills ",
  "Fort ",
  "Fortified Bridge ",
  "Fortified Underground Complex",
  "Fortress ",
  "Fraternity House ",
  "Freight Train ",
  "Freighter (ship) ",
  "Frontier Style Residence",
  "Funeral Home ",
  "Funeral in Progress",
  "Gambling Den ",
  "Game Management Area",
  "Game Preserve ",
  "Gap",
  "Garage ",
  "Garden ",
  "Gas Company ",
  "Gas Station ",
  "Gas-Fired Power Plant",
  "Gate ",
  "General Cargo Ship",
  "Geological Park",
  "Geothermal Electric Plant",
  "Geothermal Park",
  "Geyser Park",
  "Ghost Town ",
  "Glacier ",
  "Glass-Bottomed Boat ",
  "Gold Mine ",
  "Gorge",
  "Government Academy",
  "Government Office Building",
  "Government Office Complex",
  "Government Offices ",
  "Grain Elevator",
  "Grain Mill",
  "Grain Storage Bin",
  "Grassy Heights",
  "Gravel Road ",
  "Greenhouse ",
  "Grocery Store ",
  "Grotto",
  "Grove ",
  "Guard House",
  "Guard Station",
  "Gulch",
  "Gun Shop ",
  "Gymnasium",
  "Gymnasium",
  "Gymnastics Center ",
  "Halfway House",
  "Harbor ",
  "Harbormasters Office",
  "Haunted House ",
  "Haven",
  "Haven",
  "Health Club ",
  "Helicopter ",
  "Helicopter Charter",
  "Helicopter Flight School",
  "Heliport",
  "Heliport ",
  "High Speed Patrol Boat",
  "Hiking Trails",
  "Hilltop ",
  "Hi-Rise Construction Site ",
  "Historic District ",
  "Historic Monument ",
  "History Museum ",
  "Hole",
  " or Open Pit",
  "Holiday or Major Public Gathering ",
  "Hollow",
  "Homestead",
  "Horn",
  "Horse Park",
  "Horse Racing Track ",
  "Hospital ",
  "Hot Air Balloon ",
  "Hot Springs",
  "Hotel/Casino",
  "Hunter/Killer Submarine",
  "Hunting Lodge ",
  "Ice Pack ",
  "Ice Plain ",
  "Iceberg ",
  "Icebreaker Ship ",
  "Illegal Fighting Pits",
  "Import/Export Warehouse",
  "In the Eye of a Hurricane",
  "Inactive Volcano",
  "Incline Mine",
  "Incomplete Bridge ",
  "Indian Burial Grounds",
  "Indian Reservation",
  "Indoor Arena",
  "Indoor Gun Range",
  "Industrial Equipment Supply ",
  "Industrial Parts Plant",
  "Industrial Plant ",
  "Inlet ",
  "Inn ",
  "Institute",
  "Insurance Office ",
  "Intelligence Agency ",
  "Interchange ",
  "International Airport ",
  "Interstate or Highways ",
  "Interstellar Exploration Facility ",
  "Intervention Center",
  "Island Keys",
  "Jail ",
  "Jet Ski Terminal ",
  "Jetty",
  "Jewel Mine ",
  "Jewelry Shop ",
  "Junction",
  "Jungle ",
  "Jungle Isle ",
  "Junkyard ",
  "Karate Dojo ",
  "Kennel ",
  "Kennel Club",
  "Kindergarten & Daycare",
  "Knob",
  "Labor Union ",
  "Laboratory ",
  "Lagoon ",
  "Lake ",
  "Lakefront Cabin",
  "Landfill ",
  "Landing Craft (Ship)",
  "Landing Strip",
  "Large Apartment Complex ",
  "Large Canyon",
  "Large City Sewers",
  "Large Mesa ",
  "Large Office Building",
  "Large Waterfall ",
  "Laundromat ",
  "Lava Field",
  "Law Library",
  "Law Offices ",
  "Levee",
  "Library",
  "Light Buoy",
  "Light House ",
  "Lighted Data Tower",
  "Linguistics Institute",
  "Liquor Store ",
  "Listening Post ",
  "Loading Dock ",
  "Loch",
  "Lodge",
  "Log Cabin ",
  "Long Range Patrol Ship",
  "Lookout Tower",
  "Lumber Mill ",
  "Machine Shop",
  "Major Concert ",
  "Man-made Wonder ",
  "Mansion ",
  "Manufacturing Plant ",
  "Marina",
  "Marine & Boat Storage Facility ",
  "Marine Repair Facility ",
  "Marine Sanctuary ",
  "Marine Service & Fueling Station ",
  "Maritime Museum ",
  "Marketplace ",
  "Marsh ",
  "Marsh ",
  "Martial Arts Dojo ",
  "Martial Arts Facility",
  "Martial Arts Studio",
  "Mausoleum ",
  "Mausoleum Crypt",
  "Maze ",
  "Meadow",
  "Media Ceremony/ Event ",
  "Medical Center ",
  "Medical Laboratory ",
  "Medical Library",
  "Medical School ",
  "Medium Boat ",
  "Medium Office Building ",
  "Meeting House ",
  "Megalithic Ruin",
  "Memorial Library",
  "Memorial Park ",
  "Mental Health Center",
  "Mental Health Center ",
  "Merchant Ship ",
  "Metalworks Mill",
  "Microwave Relay Tower ",
  "Microwave Transmitter Tower",
  "Military Academy ",
  "Military Airbase ",
  "Military Bombing Range ",
  "Military Cruiser ",
  "Military Facility ",
  "Military Installation ",
  "Military Institute",
  "Military-Industrial Complex",
  "Mill ",
  "Mine ",
  "Missile Base ",
  "Mission (Church or Social)",
  "Mixed Jungle and Rice Paddies on Hillside Terraces",
  "Mobile Home ",
  "Mobile Home park",
  "Mobile Radar Site ",
  "Modern Bank",
  "Modern Hotel",
  "Monastery ",
  "Monument ",
  "Moon",
  "Morgue ",
  "Mosque ",
  "Motel ",
  "Motocross or Dirt Bike Raceway",
  "Motor Speedway ",
  "Motorcycle Dealership ",
  "Motorcycle Raceway ",
  "Mound ",
  "Mountain Climbing Expedition ",
  "Mountain Meadow",
  "Mountain Pass ",
  "Mountain Peak",
  "Mountain Range",
  "Mountain Spring",
  "Mountains ",
  "Mountainside Cliff ",
  "Mountainside Terraces",
  "Mountaintop ",
  "Movie Filming Location ",
  "Movie Studio ",
  "Movie Theatre ",
  "Moving Bridge ",
  "Municipal Airport",
  "Munitions Storage Facility ",
  "Narrow Canyon ",
  "National Historic Landmark ",
  "National Park ",
  "National Park Complex",
  "Native Holy Grounds ",
  "Natural Bridge ",
  "Natural Overlook ",
  "Natural Spring ",
  "Natural Wonder ",
  "Naval Station ",
  "Naval Supply Ship ",
  "Neck",
  "Newspaper ",
  "Nightclub ",
  "Nomad Camp",
  "Nuclear Attack Submarine",
  "Nuclear Plant ",
  "Nuclear Shelter Complex",
  "Nuclear Testing Ground ",
  "Nunnery",
  "Nursing Home ",
  "Oasis",
  "Observation Tower",
  "Observation Tower ",
  "Observatory ",
  "Ocean Front Bar/Tavern",
  "Ocean Liner ",
  "Ocean Storm",
  "Oceanfront Condominium",
  "Office Complex",
  "Office Tower ",
  "Oil & Gas Platform (Ocean)",
  "Oil & Gas Rig ",
  "Oil Terminal ",
  "Oilfield",
  "Old Bank ",
  "Old Hotel",
  "Old Sailing Vessel ",
  "Old Theatre ",
  "Old Town ",
  "Old Town Historical District",
  "Old U-Boat (Submarine)",
  "Open Pit ",
  "Open Pit Mine",
  "Opera Hall ",
  "Orchard ",
  "Ossuary ",
  "Outcropping",
  "Outdoor Concert",
  "Outer Space",
  "Outpost ",
  "Overnight Automobile/Passenger Ferry Ship",
  "Package Terminal ",
  "Packing Plant ",
  "Pagoda ",
  "Palace ",
  "Parachute School",
  "Paranormal Institute",
  "Park & Recreation Facility ",
  "Parking Garage ",
  "Parking Lot ",
  "Parliament",
  "Partially Buried Pyramid",
  "Passenger Cruise Ship",
  "Passenger Train ",
  "Patrol Vessel ",
  "Paved Airstrip ",
  "Pavilion ",
  "Pawnbroker ",
  "Performing Arts Awards Ceremony ",
  "Performing Arts Theatre ",
  "Pet Shop ",
  "Petroleum Manufacturing Facility ",
  "Petroleum Storage Facility ",
  "Photography Lab",
  "Picnic Area",
  "Pier ",
  "Pipeline Terminal ",
  "Pizza Palace ",
  "Placer Mine",
  "Plains or Grassland ",
  "Plant Nursery ",
  "Plant Nursery ",
  "Plastics Factory",
  "Plateau",
  "Playground ",
  "Plaza",
  "Point",
  "Police Station ",
  "Police Sub-Station",
  "Political Party HQ",
  "Political Rally ",
  "Polluted Waterway ",
  "Polo Club ",
  "Pond",
  "Pontoon Bridge ",
  "Pool",
  "Pool Hall ",
  "Post Office",
  "Post Office ",
  "Power Collection Array ",
  "Power Substation ",
  "Prep School ",
  "Preparatory School",
  "Primitive Village",
  "Print Shop ",
  "Prison ",
  "Prison Camp",
  "Prison Medical Center",
  "Private Beach ",
  "Private Golf Course ",
  "Private Home ",
  "Private Island",
  "Private Library ",
  "Private Park ",
  "Private School ",
  "Processing Facility ",
  "Protest March ",
  "Psychic Research Facility ",
  "Pub",
  "Public Beach",
  "Public Ceremony ",
  "Public Gathering ",
  "Public Golf Course ",
  "Public Library ",
  "Public Park ",
  "Publishing House",
  "Putt-Putt Golf Course ",
  "Race Track",
  "Racetrack",
  "Radio Station ",
  "Radio Telescope ",
  "Radioactive Mine ",
  "Radioactive Waste Storage Facility ",
  "Raft ",
  "Rail Yard ",
  "Railcar Wash ",
  "Railway",
  "Railway Bridge ",
  "Railway Platform ",
  "Railway Station ",
  "Railway Tunnel ",
  "Ranch ",
  "Ranger Station",
  "Rapids",
  "Recovery Ward ",
  "Recreation Area",
  "Recreation Area",
  "Recreational Vehicle ",
  "Recreational Vehicle Park",
  "Red-light District ",
  "Reef",
  "Refrigerated Ship",
  "Refrigerated Storage Facility ",
  "Regional Medical Center ",
  "Rehabilitation Center",
  "Religious Rally ",
  "Religious Retreat ",
  "Religious Sanctuary",
  "Remote Island ",
  "Remote Listening Post ",
  "Remote Research Facility ",
  "Remote Research Station ",
  "Rental Agency ",
  "Research Facility ",
  "Research Laboratory ",
  "Research Vessel ",
  "Reservoir",
  "Reservoir ",
  "Residential Construction Area ",
  "Resort ",
  "Resort",
  " Golf Course",
  " & Country Club",
  "Restaurant ",
  "Retail Store ",
  "Retirement Community",
  "Rice Paddy",
  "Ridge ",
  "Ridge ",
  "Rifle & Pistol Range ",
  "Rift Valley",
  "River ",
  "River Canyon",
  "River Ford ",
  "River Island ",
  "River Lock",
  "River Tunnel",
  "Riverbank",
  "Riverbend",
  "Riverboat (Paddlewheel) ",
  "Road ",
  "Road Fork",
  "Road Paving Company",
  "Road Tunnel ",
  "Roadside Store ",
  "Rock Garden ",
  "Rock Quarry ",
  "Rock Tower ",
  "Rocky Desert",
  "Rocky Ridges",
  "Rooftop ",
  "Rookery",
  "Rope Bridge",
  "Roundhouse (Train)",
  "Rugged Coastline ",
  "Ruins ",
  "Safari Preserve ",
  "Safe House",
  "Sailboat ",
  "Salt Flats ",
  "Salt Mine ",
  "Sand & Gravel Pit",
  "Sandbar ",
  "Sanitarium ",
  "Sargasso Sea",
  "Satellite",
  "Satellite Communications Center ",
  "Science & Industry Museum",
  "Science Institute",
  "Science Laboratory ",
  "Science Museum ",
  "Scientific Library",
  "Scrap Metal Yard",
  "Scrap Yard ",
  "Sculpture Garden ",
  "Sea Banks",
  "Sea Canyon",
  "Sea Cargo Terminal ",
  "Sea Going Hydrofoil (Ship)",
  "Sea Passenger Terminal ",
  "Sea Trench",
  "Seadrome",
  "Seaplane Base",
  "Secondary School ",
  "Secret Military Facility ",
  "Secret Stronghold ",
  "Secret Underground Stronghold ",
  "Security Center ",
  "Sewer Company",
  "Sewer Entrance ",
  "Sewers ",
  "Shaft Mine",
  "Shanty Town ",
  "Shantytown",
  "Ship Taking on Water",
  "Shipping Warehouse",
  "Shipwreck ",
  "Shipyard",
  "Shoals",
  "Shoals & Banks",
  "Shopping Center",
  "Shopping Mall ",
  "Shrine",
  "Silver Mine ",
  "Sink",
  "Sinkhole ",
  "Sinking Ship ",
  "Skateboard Rink ",
  "Skating Rink ",
  "Skating Rink ",
  "Ski Area",
  "Ski Lift ",
  "Ski Resort ",
  "Slaughterhouse",
  "Small Airport ",
  "Small Apartment Complex ",
  "Small Canyon ",
  "Small Day Passenger Ship",
  "Small Mesa ",
  "Small Office Building ",
  "Small Open Boat ",
  "Small Town",
  "Small Waterfall ",
  "Smooth Pyramid",
  "Snowfield ",
  "Snowy Crevasse ",
  "Solar Observatory ",
  "Solar Power Plant",
  "Solar System Exploration Facility ",
  "Sorority House ",
  "Spa ",
  "Space Landing Facility ",
  "Space Launch Facility ",
  "Space Station ",
  "Spacecraft ",
  "Spacecraft Repair Facility ",
  "Spanish Mission",
  "Speedboat ",
  "Sports Arena ",
  "Stables ",
  "Stadium ",
  "State Park ",
  "Station",
  "Steamship",
  "Steel Manufacturing Plant",
  "Steel Mill",
  "Stepped Pyramid",
  "Stockyard ",
  "Store ",
  "Strait or Sound ",
  "Street",
  "Strip Club ",
  "Strip Mall ",
  "Strip Mine ",
  "Structural Rubble",
  "Studio Back Lot ",
  "Sub-glacial Cave ",
  "Subterranean River",
  "Subway ",
  "Summer Camp",
  "Survivalist Enclave ",
  "Suspension Bridge ",
  "Swamp ",
  "Swimming Pool ",
  "Synagogue ",
  "Tanker (Ship)",
  "Tanning Salon",
  "Tavern ",
  "Taxi Company ",
  "Technology Gallery ",
  "Telecommunication Center ",
  "Teleconferencing Center ",
  "Telephone Company ",
  "Television Recording Studio ",
  "Television Station ",
  "Temple ",
  "Tents ",
  "Terrarium ",
  "Test Range",
  "Textiles Factory",
  "Textiles Mill",
  "The Docks ",
  "Theme Park",
  "Tire Dump ",
  "Toll Booth",
  "Toll Road",
  "Tomb ",
  "Tool Shop ",
  "Tour Bus ",
  "Town Bridge ",
  "Town Square",
  "Townhouse",
  "Toxic Waste Storage Facility ",
  "Trading Post",
  "Traffic Control Tower",
  "Trail Crossing",
  "Trailer ",
  "Trailer park",
  "Trailhead",
  "Train Depot",
  "Train Museum",
  "Train Station ",
  "Training Facility ",
  "Trash Company ",
  "Trash Dump ",
  "Travel Agency ",
  "Treatment Center",
  "Tree Nursery ",
  "Trolley ",
  "Truck Terminal ",
  "Truck Terminal ",
  "Tug Boat ",
  "Tundra",
  "Tunnel",
  "Tunnel Mine",
  "Ultralight Aircraft School",
  "Underground Bunker Complex ",
  "Underground Garage ",
  "Underground Mall ",
  "Underground Storage Facility ",
  "Underground Stronghold ",
  "Undersea Tunnel",
  "Underwater - Deep Sea ",
  "Underwater Caves & Caverns ",
  "Underwater -Coastal ",
  "Underwater Facility ",
  "Underwater Kelp Farm ",
  "Underwater Pen or Contained Area ",
  "Underwater Preserve",
  "Underwater Research Facility",
  "Union Hall ",
  "University ",
  "University Experimental Farm",
  "Unpaved Airstrip ",
  "Unusual Rock Formation",
  "Urban Fire ",
  "Urban Street ",
  "Valley ",
  "Vast Antennae Array ",
  "Vault ",
  "Vehicle Tire Store",
  "Victorian Residence",
  "Villa",
  "Village",
  "Vineyards ",
  "Volunteer Fire Department",
  "War Museum",
  "Warehouse ",
  "Warehouse District ",
  "Warm Springs",
  "Washed-Out Bridge ",
  "Washed-Out Road ",
  "Waste Water Treatment Plant ",
  "Wastewater Treatment Plant",
  "Watchtower",
  "Water Buoy",
  "Water Garden",
  "Water Garden ",
  "Water Hole",
  "Water Landing",
  "Water Park ",
  "Water Passage",
  "Water Pumping Station",
  "Water Pumping Station ",
  "Water Purification Plant ",
  "Water Tower ",
  "Water Trail",
  "Waterfront Commercial",
  "Waterfront Industrial",
  "Waterfront Restaurant",
  "Watermill",
  "Watershed",
  "Waterworks ",
  "Wax Museum ",
  "Weapons Laboratory ",
  "Wedding Hall",
  "Wedding in Progress",
  "Welcome Center",
  "Welding Equipment Store ",
  "Well ",
  "Well House",
  "Whaling Boat ",
  "Whitewater Rapids",
  "Wide Canyon ",
  "Wild Animal Park ",
  "Wilderness Park ",
  "Wildlife Refuge ",
  "Wildlife Rehabilitation Center ",
  "Wildlife Sanctuary ",
  "Windmill",
  "Winery ",
  "Woodshop ",
  "Workshop",
  "Worlds Fair ",
  "Wreck ",
  "Yacht ",
  "Yacht & Country Club",
  "Yacht Center",
  "Yacht Harbor",
  "Yacht Show",
  "Youth Camp",
  "Youth Center ",
  "Zoo"
];

const locAdj = [
  "Pure",
  "Unconscious",
  "Romantic",
  "Mere",
  "Erotic",
  "Utopian",
  "Private",
  "Poetic",
  "Wild",
  "Modern",
  "Collective",
  "Ultimate",
  "Adolescent",
  "Favorite",
  "Literary",
  "Childish",
  "Dark",
  "Popular",
  "Historical",
  "Paranoid",
  "Escapist",
  "Conscious",
  "Elaborate",
  "Secret",
  "Gothic",
  "Sadistic",
  "Imaginative",
  "Strange",
  "Delightful",
  "Pleasant",
  "Aggressive",
  "Epic",
  "Musical",
  "Wildest",
  "Primal",
  "Oriental",
  "Vivid",
  "Bizarre",
  "Impossible",
  "Contemporary",
  "Violent"
];

const peepAdj = [
  "able",
  "abnormal",
  "absent-minded",
  "above",
  "average",
  "adventurous",
  "affectionate",
  "agile",
  "agreeable",
  "alert",
  "amazing",
  "ambitious",
  "amiable",
  "amusing",
  "analytical",
  "angelic",
  "apathetic",
  "apprehensive",
  "ardent",
  "artificial",
  "artistic",
  "assertive",
  "attentive",
  "average",
  "awesome",
  "awful",
  "balanced",
  "beautiful",
  "below",
  "average",
  "beneficent",
  "blue",
  "blunt",
  "boisterous",
  "brave",
  "bright",
  "brilliant",
  "buff",
  "callous",
  "candid",
  "cantankerous",
  "capable",
  "careful",
  "careless",
  "caustic",
  "cautious",
  "charming",
  "childish",
  "childlike",
  "cheerful",
  "chic",
  "churlish",
  "circumspect",
  "civil",
  "clean",
  "clever",
  "clumsy",
  "coherent",
  "cold",
  "competent",
  "composed",
  "conceited",
  "condescending",
  "confident",
  "confused",
  "conscientious",
  "considerate",
  "content",
  "cool",
  "cool-headed",
  "cooperative",
  "cordial",
  "courageous",
  "cowardly",
  "crabby",
  "crafty",
  "cranky",
  "crass",
  "critical",
  "cruel",
  "curious",
  "cynical",
  "dainty",
  "decisive",
  "deep",
  "deferential",
  "deft",
  "delicate",
  "demonic",
  "dependent",
  "delightful",
  "demure",
  "depressed",
  "devoted",
  "dextrous",
  "diligent",
  "direct",
  "dirty",
  "disagreeable",
  "discerning",
  "discreet",
  "disruptive",
  "distant",
  "distraught",
  "distrustful",
  "dowdy",
  "dramatic",
  "dreary",
  "drowsy",
  "drugged",
  "drunk",
  "dull",
  "dutiful",
  "eager",
  "earnest",
  "easy-going",
  "efficient",
  "egotistical",
  "elfin",
  "emotional",
  "energetic",
  "enterprising",
  "enthusiastic",
  "evasive",
  "even-tempered",
  "exacting",
  "excellent",
  "excitable",
  "experienced",
  "fabulous",
  "fastidious",
  "ferocious",
  "fervent",
  "fiery",
  "flabby",
  "flaky",
  "flashy",
  "frank",
  "friendly",
  "funny",
  "fussy",
  "gassy",
  "generous",
  "gentle",
  "gloomy",
  "glutinous",
  "good",
  "grave",
  "great",
  "groggy",
  "grouchy",
  "guarded",
  "hateful",
  "hearty",
  "helpful",
  "hesitant",
  "hot-headed",
  "hypercritical",
  "hysterical",
  "idiotic",
  "idle",
  "illogical",
  "imaginative",
  "immature",
  "immodest",
  "impatient",
  "imperturbable",
  "impetuous",
  "impractical",
  "impressionable",
  "impressive",
  "impulsive",
  "inactive",
  "incisive",
  "incompetent",
  "inconsiderate",
  "inconsistent",
  "independent",
  "indiscreet",
  "indolent",
  "indefatigable",
  "industrious",
  "inexperienced",
  "insensitive",
  "inspiring",
  "intelligent",
  "interesting",
  "intolerant",
  "inventive",
  "irascible",
  "irritable",
  "irritating",
  "jocular",
  "jovial",
  "joyous",
  "judgmental",
  "keen",
  "kind",
  "lame",
  "lazy",
  "lean",
  "leery",
  "lethargic",
  "level-headed",
  "listless",
  "lithe",
  "lively",
  "local",
  "logical",
  "long-winded",
  "lovable",
  "love-lorn",
  "lovely",
  "maternal",
  "mature",
  "mean",
  "meddlesome",
  "mercurial",
  "methodical",
  "meticulous",
  "mild",
  "miserable",
  "modest",
  "moronic",
  "morose",
  "motivated",
  "musical",
  "naive",
  "nasty",
  "natural",
  "naughty",
  "negative",
  "nervous",
  "noisy",
  "normal",
  "nosy",
  "numb",
  "obliging",
  "obnoxious",
  "old-fashioned",
  "one-sided",
  "orderly",
  "ostentatious",
  "outgoing",
  "outspoken",
  "passionate",
  "passive",
  "paternal",
  "paternalistic",
  "patient",
  "peaceful",
  "peevish",
  "pensive",
  "persevering",
  "persnickety",
  "petulant",
  "picky",
  "plain",
  "plain-speaking",
  "playful",
  "pleasant",
  "plucky",
  "polite",
  "popular",
  "positive",
  "powerful",
  "practical",
  "prejudiced",
  "pretty",
  "proficient",
  "proud",
  "provocative",
  "prudent",
  "punctual",
  "quarrelsome",
  "querulous",
  "quick",
  "quick-tempered",
  "quiet",
  "realistic",
  "reassuring",
  "reclusive",
  "reliable",
  "reluctant",
  "resentful",
  "reserved",
  "resigned",
  "resourceful",
  "respected",
  "respectful",
  "responsible",
  "restless",
  "revered",
  "ridiculous",
  "sad",
  "sassy",
  "saucy",
  "sedate",
  "self-assured",
  "selfish",
  "sensible",
  "sensitive",
  "sentimental",
  "serene",
  "serious",
  "sharp",
  "short-tempered",
  "shrewd",
  "shy",
  "silly",
  "sincere",
  "sleepy",
  "slight",
  "sloppy",
  "slothful",
  "slovenly",
  "slow",
  "smart",
  "snazzy",
  "sneering",
  "snobby",
  "somber",
  "sober",
  "sophisticated",
  "soulful",
  "soulless",
  "sour",
  "spirited",
  "spiteful",
  "stable",
  "staid",
  "steady",
  "stern",
  "stoic",
  "striking",
  "strong",
  "stupid",
  "sturdy",
  "subtle",
  "sullen",
  "sulky",
  "supercilious",
  "superficial",
  "surly",
  "suspicious",
  "sweet",
  "tactful",
  "tactless",
  "talented",
  "testy",
  "thinking",
  "thoughtful",
  "thoughtless",
  "timid",
  "tired",
  "tolerant",
  "touchy",
  "tranquil",
  "ugly",
  "unaffected",
  "unbalanced",
  "uncertain",
  "uncooperative",
  "undependable",
  "unemotional",
  "unfriendly",
  "unguarded",
  "unhelpful",
  "unimaginative",
  "unmotivated",
  "unpleasant",
  "unpopular",
  "unreliable",
  "unsophisticated",
  "unstable",
  "unsure",
  "unthinking",
  "unwilling",
  "venal",
  "versatile",
  "vigilant",
  "warm",
  "warmhearted",
  "wary",
  "watchful",
  "weak",
  "well-behaved",
  "well-developed",
  "well-intentioned",
  "well-respected",
  "well-rounded",
  "willing",
  "wonderful",
  "volcanic",
  "vulnerable",
  "zealous"
];

const race = [
  "Human",
  "Elf",
  "Dwarf",
  "Orc",
  "Dragon",
  "Gnome",
  "Halfling",
  "Centaur",
  "Lizard folk",
  "Goblin",
  "Kobold",
  "Troll",
  "Gnoll",
  "Fae",
  "Ogre",
  "Mermaid",
  "Dryad",
  "Nymph",
  "Satyrs ",
  "Dark Elf",
  "Hydra",
  "Sprite",
  "Hunter",
  "Ghost",
  "Goul",
  "Goblin",
  "Drake",
  "Assasin",
  "Warlock",
  "Seer",
  "Nomad",
  "Hermit",
  "White dark knight",
  "Kitsune",
  "Angel",
  "Demon",
  "Drake",
  "Snow elve",
  "Hobgoblin",
  "Ratmen",
  "Troglodyte",
  "Cyclop",
  "Golem",
  "Slendermen",
  "Demon",
  "Angel",
  "Daemon",
  "Kami",
  "Oni",
  "Skeleton",
  "Zombie",
  "Ent",
  "treemen",
  "treefolk",
  "spriggan",
  "Sylph",
  "Salamander",
  "Werebeast",
  "shapeshifter",
  "Faerie",
  "Pixie",
  "Gryphon",
  "Hippogryph",
  "Pegasu",
  "Hippocampu",
  "Lamia",
  "Chimera",
  "Sphynx",
  "Mind Flayer",
  "Yeti",
  "Remoraz",
  "Imp",
  "Succubus"
];

const occupation = [
  "Accommodation and Hospitality Managers",
  "Accountant (General)",
  "Actuary",
  "Acupuncturist",
  "Advertising Manager",
  "Advertising Specialist",
  "Aeronautical Engineer",
  "Aeroplane Pilot",
  "Agricultural Consultant",
  "Agricultural Engineer",
  "Agricultural Scientist",
  "Agricultural Technician",
  "Airconditioning and Mechanical Services Plumber",
  "Airconditioning and Refrigeration Mechanic",
  "Aircraft Maintenance Engineer (Avionics)",
  "Aircraft Maintenance Engineer (Mechanical)",
  "Aircraft Maintenance Engineer (Structures)",
  "Ambulance Officer",
  "Amusement Centre Manager",
  "Anaesthetic Technician",
  "Anaesthetist",
  "Analyst Programmer",
  "Animal Attendants and Trainers nec",
  "Apiarist",
  "Aquaculture Farmer",
  "Arborist",
  "Architect",
  "Architectural Draftsperson",
  "Architectural, Building and Surveying Technicians nec",
  "Art Teacher (Private Tuition)",
  "Artistic Director",
  "Arts Administrator or Manager",
  "Audiologist",
  "Automotive Electrician",
  "Baker",
  "Barrister",
  "Beef Cattle Farmer",
  "Biochemist",
  "Biomedical Engineer",
  "Biotechnologist",
  "Boat Builder and Repairer",
  "Book or Script Editor",
  "Botanist",
  "Bricklayer",
  "Building and Engineering Technicians nec",
  "Building Inspector",
  "Business Machine Mechanic",
  "Butcher or Smallgoods Maker",
  "Cabinetmaker",
  "Cabler (Data and Telecommunications)",
  "Cafe or Restaurant Manager",
  "Camera Operator (Film, Television or Video)",
  "Caravan Park and Camping Ground Manager",
  "Cardiac Technician",
  "Cardiologist",
  "Cardiothoracic Surgeon",
  "Careers Counsellor",
  "Carpenter",
  "Carpenter and Joiner",
  "Cartographer",
  "Chef",
  "Chemical Engineer",
  "Chemical Plant Operator",
  "Chemist",
  "Chemistry Technician",
  "Chief Executive or Managing Director",
  "Chief Information Officer",
  "Child Care Centre Manager",
  "Chiropractor",
  "Cinema or Theatre Manager",
  "Civil Engineer",
  "Civil Engineering Draftsperson",
  "Civil Engineering Technician",
  "Clinical Coder",
  "Clinical Haematologist",
  "Clinical Psychologist",
  "Commodities Trader",
  "Community Arts Worker",
  "Community Worker",
  "Company Secretary",
  "Complementary Health Therapists nec",
  "Computer Network and Systems Engineer",
  "Conference and Event Organiser",
  "Conservation Officer",
  "Conservator",
  "Construction Estimator",
  "Construction Project Manager",
  "Contract Administrator",
  "Cook",
  "Copywriter",
  "Corporate General Manager",
  "Corporate Services Manager",
  "Cotton Grower",
  "Counsellors nec",
  "Crop Farmers nec",
  "Customer Service Manager",
  "Dairy Cattle Farmer",
  "Dance Teacher (Private Tuition)",
  "Dancer or Choreographer",
  "Database Administrator",
  "Dental Hygienist",
  "Dental Specialist",
  "Dental Technician",
  "Dental Therapist",
  "Dentist",
  "Dermatologist",
  "Developer Programmer",
  "Diagnostic and Interventional Radiologist",
  "Diesel Motor Mechanic",
  "Dietitian",
  "Director (Film, Television, Radio or Stage)",
  "Disabilities Services Officer",
  "Diversional Therapist",
  "Diving Instructor (Open Water)",
  "Dog Handler or Trainer",
  "Drainer",
  "Dressmaker or Tailor",
  "Driving Instructor",
  "Drug and Alcohol Counsellor",
  "Early Childhood (Pre-primary School) Teacher",
  "Earth Science Technician",
  "Economist",
  "Education Adviser",
  "Education Managers nec",
  "Educational Psychologist",
  "Electrical Engineer",
  "Electrical Engineering Draftsperson",
  "Electrical Engineering Technician",
  "Electrical Linesworker",
  "Electrician (General)",
  "Electrician (Special Class)",
  "Electronic Equipment Trades Worker",
  "Electronic Instrument Trades Worker (General)",
  "Electronic Instrument Trades Worker (Special Class)",
  "Electronics Engineer",
  "Emergency Medicine Specialist",
  "Emergency Service Worker",
  "Endocrinologist",
  "Engineering Manager",
  "Engineering Professionals nec",
  "Engineering Technologist",
  "Enrolled Nurse",
  "Environmental Consultant",
  "Environmental Engineer",
  "Environmental Health Officer",
  "Environmental Manager",
  "Environmental Research Scientist",
  "Environmental Scientists nec",
  "Exercise Physiologist",
  "External Auditor",
  "Facilities Manager",
  "Faculty Head",
  "Family and Marriage Counsellor",
  "Family Support Worker",
  "Farrier",
  "Fashion Designer",
  "Fibrous Plasterer",
  "Film and Video Editor",
  "Finance Broker",
  "Finance Manager",
  "Financial Brokers nec",
  "Financial Dealers nec",
  "Financial Institution Branch Manager",
  "Financial Investment Adviser",
  "Financial Investment Manager",
  "Financial Market Dealer",
  "First Aid Trainer",
  "Fitness Centre Manager",
  "Fitter (General)",
  "Fitter and Turner",
  "Fitter-Welder",
  "Flight Attendant",
  "Floor Finisher",
  "Florist",
  "Flower Grower",
  "Flying Instructor",
  "Food Technologist",
  "Footballer",
  "Forester",
  "Fruit or Nut Grower",
  "Funeral Workers nec",
  "Furniture Finisher",
  "Gallery or Museum Curator",
  "Gardener (General)",
  "Gas or Petroleum Operator",
  "Gasfitter",
  "Gastroenterologist",
  "General Practitioner",
  "Geologist",
  "Geophysicist",
  "Geotechnical Engineer",
  "Glazier",
  "Grain, Oilseed or Pasture Grower",
  "Grape Grower",
  "Graphic Designer",
  "Greenkeeper",
  "Gymnastics Coach or Instructor",
  "Hairdresser",
  "Hardware Technician",
  "Health and Welfare Services Managers nec",
  "Health Diagnostic and Promotion Professionals nec",
  "Health Information Manager",
  "Health Promotion Officer",
  "Helicopter Pilot",
  "Horse Breeder",
  "Horse Riding Coach or Instructor",
  "Horse Trainer",
  "Hospital Pharmacist",
  "Hotel or Motel Manager",
  "Human Resource Adviser",
  "Human Resource Manager",
  "Hydrogeologist",
  "ICT Account Manager",
  "ICT Business Analyst",
  "ICT Business Development Manager",
  "ICT Customer Support Officer",
  "ICT Managers nec",
  "ICT Project Manager",
  "ICT Quality Assurance Engineer",
  "ICT Sales Representative",
  "ICT Security Specialist",
  "ICT Support and Test Engineers nec",
  "ICT Support Engineer",
  "ICT Support Technicians nec",
  "ICT Systems Test Engineer",
  "ICT Trainer",
  "Illustrator",
  "Industrial Designer",
  "Industrial Engineer",
  "Industrial Pharmacist",
  "Information and Organisation Professionals nec",
  "Insurance Agent",
  "Insurance Broker",
  "Insurance Loss Adjuster",
  "Intellectual Property Lawyer",
  "Intensive Care Ambulance Paramedic",
  "Intensive Care Specialist",
  "Interior Designer",
  "Internal Auditor",
  "Interpreter",
  "Jeweller",
  "Jewellery Designer",
  "Jockey",
  "Joiner",
  "Journalists and Other Writers nec",
  "Judicial and Other Legal Professionals nec",
  "Laboratory Manager",
  "Land Economist",
  "Landscape Architect",
  "Landscape Gardener",
  "Liaison Officer",
  "Librarian",
  "Library Technician",
  "Life Science Technician",
  "Life Scientist (General)",
  "Life Scientists nec",
  "Lift Mechanic",
  "Livestock Farmers nec",
  "Locksmith",
  "Maintenance Planner",
  "Make Up Artist",
  "Management Accountant",
  "Management Consultant",
  "Manufacturer",
  "Marine Biologist",
  "Market Research Analyst",
  "Marketing Specialist",
  "Massage Therapist",
  "Materials Engineer",
  "Mathematician",
  "Meat Inspector",
  "Mechanical Engineer",
  "Mechanical Engineering Draftsperson",
  "Mechanical Engineering Technician",
  "Medical Administrator",
  "Medical Diagnostic Radiographer",
  "Medical Laboratory Scientist",
  "Medical Laboratory Technician",
  "Medical Oncologist",
  "Medical Practitioners nec",
  "Medical Radiation Therapist",
  "Medical Technicians nec",
  "Metal Fabricator",
  "Metal Fitters and Machinists nec",
  "Metal Machinist (First Class)",
  "Metallurgical or Materials Technician",
  "Metallurgist",
  "Meteorologist",
  "Microbiologist",
  "Middle School Teacher",
  "Midwife",
  "Mine Deputy",
  "Mining Engineer (excluding Petroleum)",
  "Minister of Religion",
  "Mixed Crop and Livestock Farmer",
  "Mixed Crop Farmer",
  "Mixed Livestock Farmer",
  "Motor Mechanic (General)",
  "Motorcycle Mechanic",
  "Multimedia Designer",
  "Multimedia Specialist",
  "Music Director",
  "Music Professionals nec",
  "Music Teacher (Private Tuition)",
  "Musician (Instrumental)",
  "Natural and Physical Science Professionals nec",
  "Naturopath",
  "Naval Architect",
  "Network Administrator",
  "Network Analyst",
  "Neurologist",
  "Neurosurgeon",
  "Newspaper or Periodical Editor",
  "Nuclear Medicine Technologist",
  "Nurse Educator",
  "Nurse Manager",
  "Nurse Practitioner",
  "Nurse Researcher",
  "Nurseryperson",
  "Nursing Clinical Director",
  "Nutritionist",
  "Obstetrician and Gynaecologist",
  "Occupational Health and Safety Adviser",
  "Occupational Therapist",
  "Operating Theatre Technician",
  "Ophthalmologist",
  "Optometrist",
  "Organisation and Methods Analyst",
  "Organisational Psychologist",
  "Orthopaedic Surgeon",
  "Orthoptist",
  "Orthotist or Prosthetist",
  "Osteopath",
  "Other Spatial Scientist",
  "Other Sports Coach or Instructor",
  "Otorhinolaryngologist",
  "Paediatric Surgeon",
  "Paediatrician",
  "Painting Trades Worker",
  "Panelbeater",
  "Pastrycook",
  "Patents Examiner",
  "Pathologist",
  "Pathology Collector",
  "Performing Arts Technicians nec",
  "Petroleum Engineer",
  "Pharmacy Technician",
  "Photographer",
  "Physicist ^",
  "Physiotherapist",
  "Pig Farmer",
  "Plastic and Reconstructive Surgeon",
  "Plumber (General)",
  "Podiatrist",
  "Policy Analyst",
  "Policy and Planning Manager",
  "Post Office Manager",
  "Poultry Farmer",
  "Power Generation Plant Operator",
  "Precision Instrument Maker and Repairer",
  "Pressure Welder",
  "Primary Health Organisation Manager",
  "Primary Products Inspectors nec",
  "Primary School Teacher",
  "Print Finisher",
  "Print Journalist",
  "Printing Machinist",
  "Private Tutors and Teachers nec",
  "Procurement Manager",
  "Production Manager (Forestry)",
  "Production Manager (Manufacturing)",
  "Production Manager (Mining)",
  "Production or Plant Engineer",
  "Program Director (Television or Radio)",
  "Program or Project Administrator",
  "Project Builder",
  "Property Manager",
  "Psychiatrist",
  "Psychologists nec",
  "Psychotherapist",
  "Public Relations Manager",
  "Public Relations Professional",
  "Quality Assurance Manager",
  "Quantity Surveyor",
  "Radiation Oncologist",
  "Radiocommunications Technician",
  "Real Estate Representative",
  "Records Manager",
  "Recreation Officer",
  "Recruitment Consultant",
  "Regional Education Manager",
  "Registered Nurse (Aged Care)",
  "Registered Nurse (Child and Family Health)",
  "Registered Nurse (Community Health)",
  "Registered Nurse (Critical Care and Emergency)",
  "Registered Nurse (Developmental Disability)",
  "Registered Nurse (Disability and Rehabilitation)",
  "Registered Nurse (Medical Practice)",
  "Registered Nurse (Medical)",
  "Registered Nurse (Mental Health)",
  "Registered Nurse (Paediatrics)",
  "Registered Nurse (Perioperative)",
  "Registered Nurse (Surgical)",
  "Registered Nurses nec",
  "Rehabilitation Counsellor",
  "Renal Medicine Specialist",
  "Research and Development Manager",
  "Resident Medical Officer",
  "Residential Care Officer",
  "Retail Buyer",
  "Retail Pharmacist",
  "Rheumatologist",
  "Roof Plumber",
  "Roof Tiler",
  "Safety Inspector",
  "Sales and Marketing Manager",
  "School Principal",
  "Science Technicians nec",
  "Secondary School Teacher",
  "Sheep Farmer",
  "Sheetmetal Trades Worker",
  "Ships Master",
  "Shipwright",
  "Signwriter",
  "Small Engine Mechanic",
  "Snowsport Instructor",
  "Social Professionals nec",
  "Social Worker",
  "Software and Applications Programmers nec",
  "Software Engineer",
  "Software Tester",
  "Solicitor",
  "Solid Plasterer",
  "Sonographer",
  "Sound Technician",
  "Special Education Teachers nec",
  "Special Needs Teacher",
  "Specialist Managers nec",
  "Specialist Physician (General Medicine)",
  "Specialist Physicians nec",
  "Speech Pathologist",
  "Sports Administrator",
  "Sports Centre Manager",
  "Sports Development Officer",
  "Sportspersons nec",
  "Stage Manager",
  "Statistician",
  "Stockbroking Dealer",
  "Stonemason",
  "Structural Engineer",
  "Student Counsellor",
  "Sugar Cane Grower",
  "Supply and Distribution Manager",
  "Surgeon (General)",
  "Surveying or Spatial Science Technician",
  "Surveyor",
  "Swimming Coach or Instructor",
  "Systems Administrator",
  "Systems Analyst",
  "Taxation Accountant",
  "Teacher of English to Speakers of Other Languages",
  "Teacher of the Hearing Impaired",
  "Teacher of the Sight Impaired",
  "Technical Cable Jointer",
  "Technical Director",
  "Technical Sales Representatives nec",
  "Technical Writer",
  "Telecommunications Engineer",
  "Telecommunications Field Engineer",
  "Telecommunications Linesworker",
  "Telecommunications Network Engineer",
  "Telecommunications Network Planner",
  "Telecommunications Technical Officer or Technologist",
  "Television Journalist",
  "Tennis Coach",
  "Textile, Clothing and Footwear Mechanic",
  "Thoracic Medicine Specialist",
  "Toolmaker",
  "Traditional Chinese Medicine Practitioner",
  "Translator",
  "Transport Company Manager",
  "Transport Engineer",
  "University Lecturer",
  "Upholsterer",
  "Urban and Regional Planner",
  "Urologist",
  "Valuer",
  "Vascular Surgeon",
  "Vegetable Grower",
  "Vehicle Body Builder",
  "Vehicle Painter",
  "Vehicle Trimmer",
  "Veterinarian",
  "Veterinary Nurse",
  "Video Producer",
  "Visual Arts and Crafts Professionals nec",
  "Vocational Education Teacher",
  "Wall and Floor Tiler",
  "Watch and Clock Maker and Repairer",
  "Web Administrator",
  "Web Designer",
  "Web Developer",
  "Welder (First Class)",
  "Welfare Centre Manager",
  "Welfare Worker",
  "Wine Maker",
  "Wood Machinist",
  "Wood Machinists and Other Wood Trades Workers nec",
  "Workplace Relations Adviser",
  "Youth Worker",
  "Zookeeper",
  "Zoologist"
];

const objVerbs = [
  "Advise",
  "Analyze",
  "Apply",
  "Appraise",
  "Arrange",
  "Assemble",
  "Assess",
  "Audit",
  "Calculate",
  "Categorize",
  "Change",
  "Choose",
  "Code",
  "Collect",
  "Combine",
  "Communicate",
  "Compare",
  "Compile",
  "Comply",
  "Compose",
  "Conclude",
  "Conduct",
  "Construct",
  "Contrast",
  "Convert",
  "Counsel",
  "Create",
  "Criticize",
  "Debate",
  "Deduct",
  "Defend",
  "Define",
  "Demonstrate",
  "Describe",
  "Design",
  "Develop",
  "Devise",
  "Diagram",
  "Differentiate",
  "Discover",
  "Discriminate",
  "Discuss",
  "Distinguish",
  "Dramatize",
  "Edit",
  "Employ",
  "Enforce",
  "Estimate",
  "Evaluate",
  "Examine",
  "Experiment",
  "Explain",
  "Express",
  "Extend",
  "Formulate",
  "Gather",
  "Generalize",
  "Generate",
  "Identify",
  "Illustrate",
  "Incorporate",
  "Inspect",
  "Instruct",
  "Interpret",
  "Interview",
  "Inventory",
  "Investigate",
  "Judge",
  "Justify",
  "Label",
  "List",
  "Locate",
  "Maintain",
  "Manage",
  "Manipulate",
  "Match",
  "Measure",
  "Modify",
  "Monitor",
  "Name",
  "Operate",
  "Organize",
  "Outline",
  "Paraphrase",
  "Perform",
  "Plan",
  "Point",
  "Practice",
  "Predict",
  "Prepare",
  "Produce",
  "Propose",
  "Question",
  "Rate",
  "Rearrange",
  "Recall",
  "Recommend",
  "Reconstruct",
  "Record",
  "Relate",
  "Repeat",
  "Report",
  "Reproduce",
  "Respond",
  "Restate",
  "Retrieve",
  "Review",
  "Revise",
  "Rewrite",
  "Schedule",
  "Score",
  "Screen",
  "Select",
  "Separate",
  "Show",
  "Sketch",
  "Solve",
  "State",
  "Subdivide",
  "Summarize",
  "Support",
  "Tell",
  "Test",
  "Transcribe",
  "Translate",
  "Underline",
  "Use"
];

const grouping = [
  { category: "locArray", list: locArray },
  { category: "locAdj", list: locAdj },
  { category: "peepAdj", list: peepAdj },
  { category: "race", list: race },
  { category: "occupation", list: occupation },
  { category: "objVerbs", list: objVerbs }
];

router.get("/", async (req, res) => {
  // await Collection.collection.remove();
  //
  // await Collection.collection.insertMany(grouping);

  //get all
  const collection = await Collection.find();
  res.send(collection);
});

//clear and repopulate db - testing only!
router.get("/populate", async (req, res) => {
  await Collection.collection.remove();
  await Collection.collection.insertMany(grouping);
  const collection = await Collection.find();
  res.send(collection);
});

//delete
router.put("/:id", async (req, res) => {
  const obj = await Collection.findById(req.params.id);
  if (!obj) return res.status(404).send("collection not found");

  const coll = await Collection.findByIdAndUpdate(req.params.id, {
    list: req.body.arr
  });
  if (!coll) return res.status(404).send("collection not updated");
  res.send(coll);
});
// //get one
// router.get("/:id", async (req, res) => {
//   const location = await Location.findById(req.params.id);
//   if (!location)
//     return res.status(404).send("The location with this ID was not found...");
//   res.send(location);
// });

// //put
// router.put("/:id", async (req, res) => {
//   const location = await Location.findByIdAndUpdate(
//     req.params.id,
//     { name: req.body.name },
//     { new: true }
//   );

//   if (!location)
//     return res.status(404).send("The location with this ID was not found...");
//   res.send(location);
// });

//new
// router.post("/", async (req, res) => {
//   const location = new Location({
//     name: req.body.name
//   });
//   res.send(await location.save());
// });

module.exports = router;
